// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.DAL;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(UrunDBContext))]
    partial class UrunDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication3.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"), 1L, 1);

                    b.Property<int>("KategoriAdi")
                        .HasColumnType("int");

                    b.Property<int?>("KategoriID1")
                        .HasColumnType("int");

                    b.HasKey("KategoriID");

                    b.HasIndex("KategoriID1");

                    b.ToTable("Kategoris");
                });

            modelBuilder.Entity("WebApplication3.Models.Tedarikci", b =>
                {
                    b.Property<int>("TedarikciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TedarikciId"), 1L, 1);

                    b.Property<int>("TedarikciAdi")
                        .HasColumnType("int");

                    b.HasKey("TedarikciId");

                    b.ToTable("Tedarikcis");
                });

            modelBuilder.Entity("WebApplication3.Models.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunID"), 1L, 1);

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KategoriID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunAdi")
                        .HasColumnType("int");

                    b.HasKey("UrunID");

                    b.HasIndex("KategoriID");

                    b.ToTable("Uruns");
                });

            modelBuilder.Entity("WebApplication3.Models.Kategori", b =>
                {
                    b.HasOne("WebApplication3.Models.Kategori", null)
                        .WithMany("KategoriList")
                        .HasForeignKey("KategoriID1");
                });

            modelBuilder.Entity("WebApplication3.Models.Urun", b =>
                {
                    b.HasOne("WebApplication3.Models.Kategori", "kategori")
                        .WithMany()
                        .HasForeignKey("KategoriID");

                    b.Navigation("kategori");
                });

            modelBuilder.Entity("WebApplication3.Models.Kategori", b =>
                {
                    b.Navigation("KategoriList");
                });
#pragma warning restore 612, 618
        }
    }
}
